# Generated by Django 2.0.2 on 2018-03-31 21:16

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_auto_20180330_2148'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('text', models.TextField(verbose_name='Ответ')),
                ('create_date', models.DateTimeField(default=datetime.datetime.now, verbose_name='Время ответа')),
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('is_correct', models.BooleanField(default=False, verbose_name='Корректность')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.Question', verbose_name='Вопрос')),
            ],
            options={
                'ordering': ['-create_date'],
            },
        ),
        migrations.AlterField(
            model_name='user',
            name='upload',
            field=models.ImageField(default='user.png', upload_to='uploads/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='answer',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
