# Generated by Django 2.0.2 on 2018-04-01 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0005_likeanswer'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='likes',
            field=models.IntegerField(default=0, verbose_name='Лайки'),
        ),
    ]
