# Generated by Django 2.0.2 on 2018-04-23 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0007_answer_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
